name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Package the app
        run: |
          mkdir target
          cp -r app requirements.txt run.py target/
          tar -czvf flask_app.tar.gz -C target .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/flask_app.tar.gz"
          body: "My release flask_app-3.11-${{ github.run_id }}"
          name: "Release candidate flask_app-3.11-${{ github.run_id }}"
          tag: "v3.11-${{ github.run_id }}"
